.tox:
  image: docker.io/library/python:${PYTHON_VERSION}
  before_script: pip install tox
  script: tox
  variables:
    PYTHON_VERSION: '3.10'
  needs: []

stages:
- codestyle
- test

lint:
  stage: codestyle
  extends: .tox
  variables:
    TOXENV: lint

format:
  stage: codestyle
  extends: .tox
  variables:
    TOXENV: format

pytest:
  stage: test
  extends: .tox
  variables:
    TOXENV: py
  parallel:
    matrix:
    - PYTHON_VERSION:
      - '3.9'
      - '3.10'
      - '3.11'
      - '3.12'
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: junit.xml
