image: docker.io/library/python:3.10

definitions:
  steps:
  - parallel: &codestyle
    - step:
        name: Lint
        script:
        - pip install tox
        - tox run -e lint
    - step:
        name: Format
        script:
        - pip install tox
        - tox run -e format
  - step: &unit-tests
      name: Unit Tests
      script:
      - pip install tox
      - tox run -e py

pipelines:
  branches:
    main:
    - parallel: *codestyle
    - step: *unit-tests

  pull-requests:
    '**':
    - parallel: *codestyle
    - step: *unit-tests
