definitions:
  steps:
  - parallel: &codestyle
    - step:
        name: Ruff
        script:
        - pip install tox
        - tox run -e ruff
        python: '3.10'
    - step:
        name: Format
        script:
        - pip install tox
        - tox run -e format
        python: '3.10'
  - step: &unit-tests
      name: Unit Tests
      script:
      - pip install tox
      - tox run -e py
      python:
      - '3.10'
      - '3.11'
      - '3.12'

pipelines:
  branches:
    main:
    - parallel: *codestyle
    - step: *unit-tests

  pull-requests:
    '**':
    - parallel: *codestyle
    - step: *unit-tests
