name: Pipeline

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
        - ruff
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install tox
    - run: tox run -e ${{ matrix.env }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.10'
        - '3.11'
        - '3.12'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install tox
    - run: tox run -e py
